"""Pydantic models shared by the API, the generator and the exporters."""

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# What the teacher fills in on the form (header info is NOT generated by AI)
# ---------------------------------------------------------------------------

class LessonPlanRequest(BaseModel):
    subject: str
    form: str                      # e.g. "Form One"
    activity_id: str               # id of the syllabus learning activity
    plan_format: str = "classic"   # "classic" or "tie2023"

    school_name: str = ""
    teacher_name: str = ""
    date: str = ""
    stream: str = ""               # e.g. "A"
    period_number: str = ""
    time: str = ""                 # e.g. "07:30 - 08:50"
    duration_minutes: int = 80     # single (40) or double (80) period
    boys: int = 0
    girls: int = 0
    extra_notes: str = ""          # anything the teacher wants emphasised


# ---------------------------------------------------------------------------
# What Claude generates (structured output)
# ---------------------------------------------------------------------------

class LessonStage(BaseModel):
    stage: str = Field(description="Name of the lesson development stage")
    duration_minutes: int = Field(description="Time allocated to this stage in minutes")
    teaching_activities: str = Field(description="What the teacher does, as short imperative sentences")
    learning_activities: str = Field(description="What the students do")
    assessment: str = Field(description="How achievement is checked at this stage")


class GeneratedLessonPlan(BaseModel):
    lesson_title: str = Field(description="Short title of the lesson")
    main_competence: str = Field(description="Main competence exactly as in the syllabus")
    specific_competence: str = Field(description="Specific competence exactly as in the syllabus")
    specific_objectives: list[str] = Field(description="2-4 measurable lesson objectives (ABCD format)")
    teaching_learning_resources: list[str] = Field(description="Resources, favouring locally available/improvised materials")
    references: list[str] = Field(description="Syllabus citation and approved textbook references")
    stages: list[LessonStage] = Field(description="Lesson development stages in order")
    evaluation: str = Field(description="Short guidance for the teacher's self-evaluation after the lesson")
    remarks: str = Field(description="Space-filler guidance for the remarks section")


# ---------------------------------------------------------------------------
# Full document = teacher's header + generated plan (used by exporters)
# ---------------------------------------------------------------------------

class LessonPlanDocument(BaseModel):
    request: LessonPlanRequest
    plan: GeneratedLessonPlan
