"""Pydantic models shared by the API, the generator and the exporters."""

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# What the teacher fills in on the form (header info is NOT generated by AI)
# ---------------------------------------------------------------------------

class LessonPlanRequest(BaseModel):
    subject: str
    form: str                      # e.g. "Form One"
    entry_id: str                  # scheme-of-work week, e.g. "s1w4"
    plan_format: str = "classic"   # "classic" or "tie2023"
    # Medium of instruction, for pre-primary and primary only (see
    # calendars.MEDIUM_LEVELS). TIE publishes those syllabuses in Kiswahili;
    # an English-medium school teaches the same curriculum in English, so the
    # plan — competences included — is written in English and the export says
    # the competences are a translation.
    medium: str = "kiswahili"      # "kiswahili" or "english"

    school_name: str = ""
    teacher_name: str = ""
    date: str = ""
    stream: str = ""               # e.g. "A"
    period_number: str = ""
    time: str = ""                 # e.g. "07:30 - 08:50"
    duration_minutes: int = 80     # single (40) or double (80) period
    boys: int = 0
    girls: int = 0
    extra_notes: str = ""          # anything the teacher wants emphasised

    # populated server-side from the chosen scheme-of-work week (for export)
    week_label: str = ""           # e.g. "Semester 1, Week 4 (02-Feb - 06-Feb 2026)"
    subtopic: str = ""             # the learning activity taught this week


# ---------------------------------------------------------------------------
# What Claude generates (structured output)
# ---------------------------------------------------------------------------

class LessonStage(BaseModel):
    stage: str = Field(description="Name of the lesson development stage")
    duration_minutes: int = Field(description="Time allocated to this stage in minutes")
    teaching_activities: str = Field(description="What the teacher does, as short imperative sentences")
    learning_activities: str = Field(description="What the students do")
    assessment: str = Field(description="How achievement is checked at this stage")


class GeneratedLessonPlan(BaseModel):
    lesson_title: str = Field(description="Short title of the lesson")
    main_competence: str = Field(description="Main competence exactly as in the syllabus")
    specific_competence: str = Field(description="Specific competence exactly as in the syllabus")
    main_activity: str = Field(
        default="",
        description="The scheme-of-work learning activity this lesson covers, in the "
                    "language the plan is written in",
    )
    specific_activities: list[str] = Field(
        default_factory=list,
        description="The teacher's breakdown of the main activity into the concrete "
                    "activities done in this single lesson",
    )
    teaching_learning_resources: list[str] = Field(description="Resources, favouring locally available/improvised materials")
    references: list[str] = Field(description="Approved TIE (2023 edition) book citations with page placeholders")
    stages: list[LessonStage] = Field(description="Lesson development stages in order")
    # Remarks is a post-lesson field on the TIE form: the teacher writes it after
    # teaching. Pre-filling it makes the plan claim things that have not happened
    # yet ("all 47 students participated"), which is false in a document that goes
    # to inspection — so it is always exported blank for the teacher to complete.
    remarks: str = Field(
        default="",
        description="Always return an empty string; the teacher writes this after "
                    "teaching the lesson",
    )


# ---------------------------------------------------------------------------
# Full document = teacher's header + generated plan (used by exporters)
# ---------------------------------------------------------------------------

class LessonPlanDocument(BaseModel):
    request: LessonPlanRequest
    plan: GeneratedLessonPlan
